# `%s` represents where the search query goes
# NOTE: Could omit this since it doesn't really matter... just append query content after eq
default_search = "https://duckduckgo.com/"

[[shortcut]]
keyword = "rs"
url = "https://docs.rs/"
search_url = "https://docs.rs/releases/search?query="
